apiVersion: v1
kind: Service
metadata:
  name: rapheebeauty-svc-dev
  namespace: dev-namespace
spec:
  selector:
    app: rapheebeauty-dev
  ports:
    - port: 8000
      targetPort: 8000
      # nodePort: 30009
  type: NodePort
