apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapheebeauty
  namespace: prod-namespace
  labels:
    app: rapheebeauty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rapheebeauty
  template:
    metadata:
      labels:
        app: rapheebeauty
    spec:
      containers:
        - name: rapheebeauty-latest
          image: blesseddocker/ifeoma-rapheebeauty:prod
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "1000Mi"
              cpu: "500m"
            requests:
              memory: "500Mi"
              cpu: "250m"
          env:
          - name: MYSQL_HOST
            value: 216.80.104.71
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            value: devops2023
          - name: MYSQL_DATABASE
            value: rapheebeauty
