apiVersion: v1
kind: Service
metadata:
  name: rapheebeauty-svc-prod
  namespace: prod-namespace
spec:
  selector:
    app: rapheebeauty-prod
  ports:
    - port: 8000
      targetPort: 8000
      # nodePort: 30009
  type: NodePort
