apiVersion: v1
kind: Service
metadata:
  name: rapheebeauty-svc-qa
  namespace: qa-namespace
spec:
  selector:
    app: rapheebeauty-qa
  ports:
    - port: 8000
      targetPort: 8000
      # nodePort: 30009
  type: NodePort
